Repository uwasystemhealth/FRACAS_Team1, pull requests merged in 2023-10, with the labels that each got.

#61 Backend API documentation done, fixed permission bug
  backend/README.md
  backend/api/permissions.py
Labels: documentation, server-side-app

#69 Fix #66 User-specific record editing permissions
  backend/README.md
  backend/api/models.py
  backend/api/permissions.py
  backend/api/serializers.py
Labels: documentation, enhancement, server-side-app

#82 Frontend record statuses buttons functional
  fracas-ui/src/pages/Report.js
  fracas-ui/src/pages/ViewEdit.js
  fracas-ui/src/styles/Report.scss
  fracas-ui/src/styles/ViewEdit.scss
  fracas-ui/yarn.lock
Labels: client-side-app

#83 Forgotten password
  fracas-ui/public/favicon.ico
  fracas-ui/public/logo192.png
  fracas-ui/public/logo512.png
  fracas-ui/src/App.js
  fracas-ui/src/pages/Activation.js
  fracas-ui/src/pages/ForgotPassword.js
  fracas-ui/src/pages/ResetPassword.js
  fracas-ui/src/pages/SearchReports.js
Labels: client-side-app

#88 Frontend record editors & page elements wordings.
  fracas-ui/src/pages/Report.js
  fracas-ui/src/pages/ViewEdit.js
  fracas-ui/src/styles/Report.scss
  fracas-ui/src/styles/ViewEdit.scss
Labels: client-side-app, enhancement
